pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://download2.dynamsoft.com/maven/aar"
        }
    }
}

include ':app'
rootProject.name = "CameraX Minimum"
